### PR TITLE
added language name bottom of card

### PR DESCRIPTION
**Pull request by NarHakobyan**
it's more comfortable to see language name under repository 😄

### CODE REVIEW

**Comment by NarHakobyan** [comment]
@beeman @hanford ? :)

**Comment by hanford** [comment]
I added this and decided not to ship it because I figured most people would save a language and then continually go back to that one. (in my case, I mostly care about javascript) and if my assumption is correct this is a little redundant.

What are your thoughts?

**Comment by NarHakobyan** [comment]
@hanford yes but it's more comfortable when seeing in which language was written trending repository, mostly when I am in "all" list

**Comment by hanford** [comment]
@NarHakobyan perhaps we could modify the PR and only show the language when the user is looking at that list

**Comment by NarHakobyan** [comment]
@hanford I thought so too, but I think it's not user-friendly to see some part of info only in full list, but if you want I can modify

**Comment by hanford** [comment]
Going to keep it as just the color I think - Appreciate the PR though! ❤️

**Pull request closed without merging**
