### PR TITLE
add TypeScript

### LINKED ISSUE #8: TypeScript
Could you please add TypeScript repos? :)

### PR DESCRIPTION
**Pull request by beeman**
Fixes #8

### CODE REVIEW

**Comment by hanford** [comment]
thanks!

**Comment by hanford** [comment]
not really obvious, but i added this btw: https://github.com/hanford/trends/commit/204435e786f930b83b7316754596ea5e6a8788a5

**Comment by hanford** [comment]
it's live btw!

**Comment by beeman** [comment]
Thanks for the fix and the quick merge  👍🏼

**Pull request merged**
